export const films = [
  {
    id: 'drive',
    name: 'Drive',
    year: 2011,
    tagline: 'There are no clean getaways.',
    quote: '"There\'s a hundred-thousand streets in this city. You don\'t need to know the route. You give me a time and a place, I give you a five minute window."',
    color: '#e84393',
    bgColor: '#0a0a2e',
    video: ['https://github.com/Younginspace/gosling-cinema/releases/download/v1.0-assets/drive1-1.mov', 'https://github.com/Younginspace/gosling-cinema/releases/download/v1.0-assets/drive2.mov'],
    effects: { bloom: 1.5, chromatic: 0.008, sepia: 0.0, noise: 0.12, vignette: 0.8, scanline: 0.15 },
    tint: [0.91, 0.26, 0.58],
  },
  {
    id: 'blade-runner',
    name: 'Blade Runner 2049',
    year: 2017,
    tagline: 'The key to the future is finally unearthed.',
    quote: '"I\'ve seen things you people wouldn\'t believe... All those moments will be lost in time, like tears in rain."',
    color: '#e17055',
    bgColor: '#1a0a00',
    video: 'https://github.com/Younginspace/gosling-cinema/releases/download/v1.0-assets/2049.mov',
    effects: { bloom: 0.8, chromatic: 0.003, sepia: 0.15, noise: 0.2, vignette: 1.0, scanline: 0.08 },
    tint: [0.88, 0.44, 0.13],
  },
  {
    id: 'la-la-land',
    name: 'La La Land',
    year: 2016,
    tagline: 'Here\'s to the fools who dream.',
    quote: '"I\'m letting life hit me until it gets tired. Then I\'ll hit back. It\'s a classic rope-a-dope."',
    color: '#6c5ce7',
    bgColor: '#0d0030',
    video: 'https://github.com/Younginspace/gosling-cinema/releases/download/v1.0-assets/lalaland.mov',
    effects: { bloom: 1.2, chromatic: 0.002, sepia: 0.0, noise: 0.06, vignette: 0.5, scanline: 0.05 },
    tint: [0.42, 0.36, 0.91],
  },
  {
    id: 'barbie',
    name: 'Barbie',
    year: 2023,
    tagline: 'She\'s everything. He\'s just Ken.',
    quote: '"I\'m just Ken. Anywhere else I\'d be a ten. Is it my destiny to live and die a life of blonde fragility?"',
    color: '#fd79a8',
    bgColor: '#2d0020',
    video: 'https://github.com/Younginspace/gosling-cinema/releases/download/v1.0-assets/barbie.mov',
    effects: { bloom: 1.0, chromatic: 0.001, sepia: 0.0, noise: 0.04, vignette: 0.3, scanline: 0.03 },
    tint: [0.99, 0.48, 0.66],
  },
  {
    id: 'hail-mary',
    name: 'Project Hail Mary',
    year: 2026,
    tagline: 'A lone astronaut must save Earth.',
    quote: '"I\'m Ryland Grace, and I have a very important mission... I just can\'t remember what it is."',
    color: '#74b9ff',
    bgColor: '#020810',
    video: 'https://github.com/Younginspace/gosling-cinema/releases/download/v1.0-assets/phm.mov',
    effects: { bloom: 0.6, chromatic: 0.005, sepia: 0.0, noise: 0.08, vignette: 0.9, scanline: 0.1 },
    tint: [0.18, 0.45, 0.92],
  },
];
